---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: <%= name %>
    app.kubernetes.io/part-of: <%= name %>
    gitops-source-sha: "%GITOPS_SOURCE_SHA%"
  name: <%= name %>
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: <%= serviceTargetPort %>
  - name: admin
    port: 8081
    protocol: TCP
    targetPort: admin
  selector:
    app.kubernetes.io/name: <%= name %>
  type: ClusterIP
